[package]
name = "syscalls_shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.26.2"
protocol = { version = "3.4", features = ["derive"] }
