[package]
name = "data_exploration_nannou"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.18"
serde = "1.0"
serde_json = "1.0"
nom = "7"
