version: "3"

services:
  server:
    build: .
    restart: always
    command: pm2-runtime ecosystem.config.js --only server
    env_file:
      - ./.env
    environment:
      - REDIS_HOSTNAME=redis
      - DB_HOSTNAME=mongodb
      - DB_PORT=27017
    volumes:
      - .:/app
    ports:
      - "$SERVER_PORT:$SERVER_PORT"
    links:
      - mongodb
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
  screen:
    build: .
    restart: always
    command: pm2-runtime ecosystem.config.js --only screen
    privileged: true
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    env_file:
      - ./.env
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:$SCREEN_PORT:$SCREEN_PORT"
    depends_on:
      - server
    links:
      - server
    extra_hosts:
      - "host.docker.internal:host-gateway"


  mongodb:
    image: mongo:latest
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - "127.0.0.1:27000:27017"
    command: --quiet
    healthcheck:
      test:
        - CMD
        - mongo
        - --eval
        - "db.adminCommand('ping')"
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    image: "redis:alpine"
volumes:
  mongodb_data_container:
